version: "3.9"

services:
  gateway:
    restart: always
    image: nginx:1.15
    volumes:
      - "./nginx/nginx.conf:/etc/nginx/conf.d/default.conf:ro"
    links:
      - frontend:frontend
      - backend:backend
    ports:
      - "80:80"
      - "443:443"

  backend: &backend
    restart: always
    build: .
    working_dir: /app
    expose:
      - 5000
    volumes:
      - ./server:/app
    ports:
      - 5000:5000
    depends_on:
      - mongo
    environment:
      API_PORT:
      DATABASE_URI:
      TOKEN_KEY:
      EMAIL_SENDER_SERVICE:
      EMAIL_SENDER_USERNAME:
      EMAIL_SENDER_PASSWORD:
    command: bash -c "npm install && npm run dev"

  frontend: &frontend
    restart: always
    build: .
    working_dir: /app
    expose:
      - 3000
    ports:
      - "3000:3000"
    volumes:
      - "./client:/app"
    depends_on:
      - backend
    command: bash -c "npm install && npm run start"

  mongo:
    image: mongo:5
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME:
      MONGO_INITDB_ROOT_PASSWORD:
    volumes:
      - mongodb:/data/db

  mongo-express:
    restart: unless-stopped
    image: mongo-express
    ports:
      - 8081:8081
    depends_on:
      - mongo
    environment:
      ME_CONFIG_MONGODB_SERVER:
      ME_CONFIG_MONGODB_AUTH_USERNAME:
      ME_CONFIG_MONGODB_AUTH_PASSWORD:

networks:
  default:
    name: mongo-express-network

volumes:
  mongodb:
