version: "3.9"

services:
  backend:
    restart: always
    build: ./server
    volumes:
      - "./app/node_modules"
      - ./server:/app
    ports:
      - 5000:5000
    depends_on:
      - mongo
    environment:
      API_PORT: 5000
      DATABASE_URI: mongodb://root:example@mongo:27017
      TOKEN_KEY: "SecretKey"

  mongo:
    image: amd64/mongo:4
    restart: always
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    volumes:
      - mongodb:/data/db

  frontend:
    build: ./client
    restart: always
    ports:
      - "3000:3000"
    volumes:
      - "./app/node_modules"
      - "./client:/app"
    depends_on:
      - backend

volumes:
  mongodb:
