version: "3.9"

services:
  backend:
    restart: always
    image: node:18
    working_dir: /app
    volumes:
      - .:/app
    depends_on:
      - mongo
    expose:
      - 5000
    ports:
      - 5000:5000
    environment:
      API_PORT: 5000
      DATABASE_URI: mongodb://root:example@mongo:27017
      TOKEN_KEY: "SecretKey"
    command: bash -c "cd client && npm install && chmod -R 777 node_modules/ && npm run build && cd ../server && npm install && npm run prod"

  mongo:
    image: amd64/mongo:4
    restart: always
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    volumes:
      - mongodb:/data/db

volumes:
  mongodb:
