version: "3.9"

services:
  backend:
    restart: always
    image: .
    working_dir: /app
    volumes:
      - .:/app
    depends_on:
      - mongo
    expose:
      - 5000
    ports:
      - 5000:5000
    environment:
      API_PORT:
      DATABASE_URI:
      TOKEN_KEY:
    command: bash -c "cd client && npm install && npm run build && cd ../server && npm install && npm run prod"

  mongo:
    image: mongo:5
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME:
      MONGO_INITDB_ROOT_PASSWORD:
    volumes:
      - mongodb:/data/db

  mongo-express:
    restart: unless-stopped
    image: mongo-express
    ports:
      - 8081:8081
    depends_on:
      - mongo
    environment:
      ME_CONFIG_MONGODB_SERVER:
      ME_CONFIG_MONGODB_AUTH_USERNAME:
      ME_CONFIG_MONGODB_AUTH_PASSWORD:

volumes:
  mongodb:
